apiVersion: v1
kind: Namespace
metadata:
  name: argocd
  labels:
    kubernetes.io/metadata.name: argocd
    # This label lets ArgoCD manage resources in its own namespace
    app.kubernetes.io/managed-by: argocd
